### PR TITLE
landing page draft copy to use as a base for changes

### PR DESCRIPTION
**Pull request by jsoverson**
As demoed, this is the sample landing page copy with modifications to the arch diagram requested during the wasmcloud community call.

This PR is sample, best-effort copy. It is meant to be a baseline that is better than the generic template copy that is on wapc.io now. @pkedy (& @autodidaddict) know the history & motivations behind wapc and know what changes should be made. It's easier to look at something and say "no, that's wrong, this should be that" vs looking at nothing and figuring out what should be there.

### CODE REVIEW

**Comment by autodidaddict** [comment]
Difficult to see what this looks like when the netlify build failds

**Comment by jsoverson** [comment]
@autodidaddict  updated the dependencies which fixed the postcss failure. Site is viewable.

Don't worry about hurting my feelings when viewing it. I stretched passed what I felt comfortable writing just to get something together. Cut it up as you want.

**Comment by autodidaddict** [comment]
LGTM but I'll leave it up to @pkedy for the detailed picking of nits

**Comment by jsoverson** [comment]
Did another pass at it since it's been sitting. I removed the stub content in /docs and replaced it with links to waPC host/guest repos, community projects (i.e. wasmcloud), links to wasmcloud's waPC reference, links to the validator, and links to getting started tutorials.

I simplified some of the front page copy and adjusted some styles for readability.

**Comment by autodidaddict** [comment]
Content awaiting your approval @pkedy

**Pull request merged**
